name: petty_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS styling
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.4.6

  # Supabase integration
  supabase_flutter: ^1.10.21

  # Maps & Location
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^10.1.0

  # Media & animations
  image_picker: ^1.2.0
  rive: ^0.13.20

  # Apple Sign-In
  sign_in_with_apple: ^7.0.1
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sign_in_with_apple: 7.0.1
  sign_in_with_apple_platform_interface: 2.0.0
  sign_in_with_apple_web: 3.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rive/login_animation.riv
    - assets/rive/bunny_animation.riv
    - assets/rive/panda_2_animation.riv
    - assets/images/chatlogo.jpg
    - assets/images/google.png
