services:
  pet-api:
    image: localhost/pet-api:latest
    container_name: pet-api
    ports:
      - "19911:19911"
    volumes:
      - pet-data:/app/data
    restart: unless-stopped

volumes:
  pet-data:
